version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-reserve}
      POSTGRES_USER: ${POSTGRES_USER:-reserve}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supersecret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - backups:/backups
    # Bind to host 5433 by default to avoid collision with locally installed PostgreSQL service on 5432
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-reserve}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - .env.prod
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "3003"

  market:
    build:
      context: .
      dockerfile: apps/market/Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      api:
        condition: service_started
    expose:
      - "3000"

  admin:
    build:
      context: .
      dockerfile: apps/b2b-console/Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      api:
        condition: service_started
    expose:
      - "3001"

  widget:
    build:
      context: .
      dockerfile: apps/booking-widget/Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      api:
        condition: service_started
    expose:
      - "3002"

  provider:
    build:
      context: .
      dockerfile: apps/provider/Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      api:
        condition: service_started
    expose:
      - "3004"

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      api:
        condition: service_started
      market:
        condition: service_started
      admin:
        condition: service_started
      widget:
        condition: service_started
      provider:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/nginx/certs:/etc/nginx/certs:ro

volumes:
  postgres_data:
  backups:
